AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude: &fastfiles
    - fastlane/Fastfile
    - fastlane/lanes/*.rb

Layout/LineLength:
  Max: 180
  Exclude: *fastfiles

Layout/EmptyLines:
  Exclude: *fastfiles

Style/AsciiComments:
  Exclude: *fastfiles

Naming/FileName:
  Exclude:
    - fastlane/Matchfile
