common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - $CI_TOOLKIT_PLUGIN

env:
  IMAGE_ID: $IMAGE_ID

# The code freeze completion needs to run on macOS because it uses genstrings under the hood
agents:
    queue: mac

steps:
  - label: Complete Code Freeze
    key: complete_code_freeze
    plugins: *common_plugins
    command: ".buildkite/commands/complete-code-freeze.sh $RELEASE_VERSION"

  - label: Log Outdated Pods
    depends_on: complete_code_freeze
    plugins: *common_plugins
    command: ".buildkite/commands/log-outdated-pods.sh $RELEASE_VERSION"
