steps:
  - label: Finalize Release
    plugins:
      - $CI_TOOLKIT_PLUGIN
    # The finalization needs to run on macOS because of localization linting
    agents:
        queue: mac
    env:
      IMAGE_ID: $IMAGE_ID
    command: ".buildkite/commands/finalize-hotfix.sh $VERSION"
